### ISSUE TITLE
User can see the landing page

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/ajax-project#1]
## 💰 Motivation

A dynamic application for outdoor photographers that includes a field journal and utilizes APIs for weather and astronomical data.

## 📐 Plan

Outdoor photographers will be able to enter a zip code to find weather and astrological data for a shooting location.

## Wireframe 
![image](https://user-images.githubusercontent.com/73143959/108886815-46faa700-75be-11eb-8c9e-34d1d8c9d1a9.png)

## ✅ Task List

- [x] Add font awesome link to head
- [x] Add div to HTML for landing view
- [x] Add images folder
- [x] Add image and text content
- [x] Add nav bar
- [x] Add form input for zip code
- [x] Add CSS layout
- [x] Add CSS styling
