### ISSUE TITLE
User can request weather and astronomical data by zip code

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/ajax-project#2]
## 💰 Motivation

A dynamic application for outdoor photographers that includes a field journal and utilizes APIs for weather and astronomical data.

## 📐 Plan

Outdoor photographers will be able to enter a zip code to find weather and astrological data for a shooting location.

## Wireframe 
![image](https://user-images.githubusercontent.com/73143959/108904776-c9419600-75d3-11eb-8a87-539325f819ea.png)

## ✅ Task List
- [x] Add div to HTML for plan view
- [x] Add header
- [x] Add ul for astro data
- [x] Add ul for weather data
- [x] Add form input for zip code
- [x] Add CSS styling
- [x] Add JS function to change views
- [x] Add event listener to plan link to change view
- [x] Add object literals for weather and astro data
- [x] Add JS function to request astro data from API and add to data model
- [x] Add JS function to request weather data from API and add to data model
- [x] Add JS functionality to add astro data to DOM
- [x] Add JS functionality to add weather data to DOM
- [x] Add event listener to form input on landing page
- [x] Add data to local storage
