### ISSUE TITLE
User can take field notes

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/ajax-project#3]
## 💰 Motivation

A dynamic application for outdoor photographers that includes a field journal and utilizes APIs for weather and astronomical data.

## 📐 Plan

User can take field notes to record conditions and camera settings and equipment

## Wireframe

![image](https://user-images.githubusercontent.com/73143959/109059653-513da380-7699-11eb-85e7-dce05ab2fc3b.png)

## ✅ Task List
- [x] Add div to HTML for record view
- [x] Add form inputs
- [x] Add save button
- [x] Add JS function to change to record view
- [x] Add CSS styling
- [x] Add data model for field notes
- [x] Add JS function to add new note to data model
- [x] Add note data to local storage
