### ISSUE TITLE
User can see previous notes

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/ajax-project#4]
## 💰 Motivation

A dynamic application for outdoor photographers that includes a field journal and utilizes APIs for weather and astronomical data.

## 📐 Plan

User can see all their field notes.

## Wireframe

![image](https://user-images.githubusercontent.com/73143959/109081772-a4265380-76b7-11eb-9a84-8ff61980eaf0.png)

## ✅ Task List
- [x] Add div to HTML for review view
- [x] Add ul for field notes
- [x] Add JS function to change to review view
- [x] Add JS function to render notes
- [x] Add CSS styling
- [x] Add functionality to swap to review view on new note submit
