### ISSUE TITLE
User can edit field notes

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/ajax-project#5]
## 💰 Motivation

A dynamic application for outdoor photographers that includes a field journal and utilizes APIs for weather and astronomical data.

## 📐 Plan

User can edit previously entered field notes

## ✅ Task List
- [x] Add edit icon to review view
- [x] Add JS function to populate edit form with note data
- [x] Add JS function to replace edited note in data model
- [x] Add JS function to replace edited note in DOM
