### ISSUE TITLE
User can delete field notes

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/ajax-project#6]
## 💰 Motivation

A dynamic application for outdoor photographers that includes a field journal and utilizes APIs for weather and astronomical data.

## 📐 Plan

User can delete previously entered field notes.

## ✅ Task List
- [x] Add delete icon to review view
- [x] Add div to HTML for delete confirmation modal with two icons
- [x] Add CSS modal styling
- [x] Add JS function to view modal on delete icon click
- [x] Add JS function to close modal on cancel
- [x] Add JS function to delete note from data model and DOM on confirm
