### ISSUE TITLE
User can add favorite gear

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/ajax-project#7]
## 💰 Motivation

A dynamic application for outdoor photographers that includes a field journal and utilizes APIs for weather and astronomical data.

## 📐 Plan

User can add their cameras, filters, and lenses and these options will available to them as drop down select options when creating a new field note.

## ✅ Task List
- [x] Add div to HTML for gear view
- [x] Add ul for each category
- [x] Add form input and icon for each category
- [x] Add JS function to change to gear view
- [x] Add CSS Styling
- [x] Add data model for gear
- [x] Add JS function to add new gear to data model
- [x] Add JS function to render new gear
- [x] Add to local storage
- [x] Change gear inputs to select
- [x] Add JS function to add new gear as select option
- [x] Make last selected gear the default option for that session
- [x] Add additional styling
