### ISSUE TITLE
User can delete favorite gear

### ISSUE THREAD

**Issue by KiraHike** [KiraHike/ajax-project#8]
## 💰 Motivation

A dynamic application for outdoor photographers that includes a field journal and utilizes APIs for weather and astronomical data.

## ✅ Task List
- [x] Add delete icon to each item
- [x] Add JS function to show delete modal
- [x] Add JS function to close modal on cancel
- [x] Add JS function to delete item from data model, and gear list on confirm
- [x] Add JS function to delete item from select option
